import type { BuildingKind, ResourceId, TroopKind } from '../game/map'
import type {
  AiLayoutKind,
  AiOpeningKind,
  AiProfileRules,
  AiSettlementZoneKind,
} from '../game/ai/model'

export const aiPlannerConfig = {
  softBudgetMs: 3_000,
  hardBudgetMs: 10_000,
  deadlineSafetyMarginMs: 25,
  nodeBudget: 24_000,
  goalValidationNodeBudget: 384,
  projectionTurns: 4,
  stableRecoveryTurns: 3,
  foodRunwayTurns: 3,
  assaultFoodRunwayTurns: 4,
  goldRunwayTurns: 3,
  targetChangeMargin: 0.18,
  readinessEstimateTolerance: 0.03,
  targetMemoryTurns: 8,
  maximumRememberedContacts: 256,
  maximumBlockedCells: 32,
  blockedCellMemoryTurns: 2,
  maximumCommands: 18,
  minimumTaxHoldTurns: 3,
  forcedAdvanceAfterIdleTurns: 2,
  stalledMobilizationProbeTurns: 6,
  retargetAfterIdleTurns: 6,
  relaxBlueprintAfterStalledTurns: 4,
  armyReorganizationCooldownTurns: 4,
  ordinaryTacticalOrderReserve: 2,
  assaultOrderReserve: 4,
  strategicSearchDepth: 3,
  strategicBeamWidth: 6,
  candidatePriorScale: 0.12,
  candidatePriorLimit: 24,
  sequenceLengthBonus: 3,
  tacticalGuardMultiplier: 2,
  forcedAdvanceMinimumScore: -80,
  emergencyRunwayTurns: 1.5,
  defenseSupplyUtilityBonus: 20,
  defenseRecruitUtilityBonus: 35,
  productiveTradeRunwayDelta: 0.5,
} as const

export const aiBuildingKindsByZone = {
  housing: ['house', 'kitchen', 'market', 'church'],
  food: ['orchard', 'huntingLodge', 'mill', 'farm'],
  industry: ['lumberMill', 'quarry', 'mine', 'smelter'],
  military: ['barracks'],
  defense: ['wall', 'tower', 'barbican'],
} as const satisfies Record<AiSettlementZoneKind, readonly BuildingKind[]>

export const aiBuildingZoneByKind = Object.fromEntries(
  (Object.entries(aiBuildingKindsByZone) as Array<[AiSettlementZoneKind, readonly BuildingKind[]]>)
    .flatMap(([zone, kinds]) => kinds.map((kind) => [kind, zone])),
) as Record<BuildingKind, AiSettlementZoneKind>

export const aiSpatialConfig = {
  visibilityRayLength: 10,
  choke: {
    blockedNeighborBase: 4,
    blockedNeighborWeight: 7,
    frontLineBase: 8,
    frontLineDistanceWeight: 0.08,
  },
  layoutScore: {
    courtyard: { plain: 100, passableCap: 30, passableDivisor: 20, choke: -1 },
    frontier: { mixedTerrain: 65, distanceCap: 35, distance: 0.5 },
    strongpoint: { choke: 4, hill: 70, nonPlain: 20 },
  },
  openingScore: {
    forest: { coverage: 130, nearbyDistance: 12, proximity: 4 },
    plains: { coverage: 110 },
    highland: { coverage: 130, nearbyDistance: 12, proximity: 4 },
  } satisfies Record<AiOpeningKind, Record<string, number>>,
  preferenceBonus: 2,
  preferredSiteDistance: { housing: 3, food: 6, industry: 6, industryFallback: 7, military: 4 },
  gateCorridorShare: 0.35,
  regionScale: { minimum: 0.8, maximum: 1.35, referenceCells: 1_200, mediumThreshold: 1.12, largeThreshold: 1.32 },
  regionOriginGrowth: { medium: 1, large: 2 },
  minimumZoneArea: 8,
  baseZoneArea: { housing: 18, food: 28, industry: 18, military: 15, defense: 16 } satisfies Record<AiSettlementZoneKind, number>,
  layoutAreaScale: {
    courtyard: { housing: 1.12, food: 1.08, industry: 0.9, military: 1, defense: 0.82 },
    frontier: { housing: 1, food: 1, industry: 1.12, military: 1.05, defense: 1.05 },
    strongpoint: { housing: 0.92, food: 0.94, industry: 1, military: 1.12, defense: 1.28 },
  } satisfies Record<AiLayoutKind, Record<AiSettlementZoneKind, number>>,
  cellsPerOrigin: { housing: 2.5, food: 4, industry: 2, military: 6, defense: 1.5 } satisfies Record<AiSettlementZoneKind, number>,
  hillOpportunityCost: { base: 18, scarcity: 45 },
  settlementPlan: {
    scoreTieEpsilon: 0.0001,
    profileSeedMultiplier: 31,
    siteChokeWeight: 0.05,
    ordinaryHillPenalty: 5,
    industryMissingTerrainPenalty: 3,
    defenseChokeWeight: -0.08,
    ordinaryChokeWeight: 0.04,
  },
} as const

export const aiStrategicConfig = {
  workerReserve: 2,
  populationGrowthLookahead: 2,
  maximumBuildingGoalsPerSearch: 6,
  buildingPlacementShortlist: 1_200,
  adaptiveBlueprintExpansionLimit: 4,
  maximumFoodFallbackBuildings: 2,
  minimumRunwayFlowMagnitude: 0.5,
  minimumCivilianReserve: 2,
  defenseWorkerReserveShare: 0.5,
  maximumRecruitBatch: 3,
  recruitmentCellCapacity: 10,
  basicMilitiaBeforeBarracks: 2,
  minimumAdvancedTroopsForPreferredArmy: 2,
  emergencyFoodBatch: 5,
  constructionWoodFloor: 20,
  operationalFoodBuildings: ['orchard', 'huntingLodge', 'farm'] as readonly BuildingKind[],
  crisisProductionBuildings: ['orchard', 'huntingLodge', 'farm', 'mill', 'kitchen', 'lumberMill'] as readonly BuildingKind[],
  restorableCapabilities: [
    'orchard', 'huntingLodge', 'mill', 'farm', 'kitchen', 'house',
    'lumberMill', 'quarry', 'mine', 'smelter', 'market', 'barracks',
  ] as readonly BuildingKind[],
  basicFoodBuildings: ['orchard', 'huntingLodge'] as readonly BuildingKind[],
  minimumFieldArmySize: 4,
  openingBuildingBonus: {
    forest: { huntingLodge: 20, lumberMill: 16, orchard: -4 },
    plains: { orchard: 18, mill: 14, farm: 14, huntingLodge: -4 },
    highland: { quarry: 18, mine: 14, orchard: 2, huntingLodge: 2 },
  } satisfies Record<AiOpeningKind, Partial<Record<BuildingKind, number>>>,
  threat: {
    immediateRadius: 12,
    evaluationRadius: 16,
    assumedOrdersPerTurn: 8,
    maximumArrivalTurns: 2,
  },
  power: {
    troopDamageWeight: 1.8,
    archerRangeBonus: 0.65,
    knightMobilityPenalty: 0.08,
    minimumHealthShare: 0.45,
    remainingHealthShare: 0.55,
    towerGarrisonMultiplier: 1.2,
  },
  phase: {
    regroupMinimumPower: 6,
    regroupTargetRatio: 0.55,
    campaignGoldRunway: 2,
    directDoctrineManeuverCutoff: 0.5,
    agileProbePowerCap: 6.5,
    assemblyBaseShare: 0.65,
    assemblyManeuverDiscount: 0.2,
  },
  targetPower: {
    minimum: 8,
    castleBase: 8,
    castleHealthWeight: 0.04,
    wall: 3,
    barbican: 2,
    towerBase: 5,
    towerGarrisonArcher: 1.5,
  },
  targetSelection: {
    distanceWeight: 1.2,
    defensePowerWeight: 0.35,
    castleDamageWeight: 0.8,
    retaliationWindow: 8,
    stickinessScale: 20,
    minimumMemoryConfidence: 0.45,
  },
  resourcePlanning: {
    needWeights: { wood: 0.45, stone: 0.45, ore: 0.45, iron: 2, flour: 0.45, meat: 0.45, fruit: 0.45, gold: 1.3 } satisfies Record<ResourceId, number>,
    allowedBuildingBonus: 8,
    unavailableBuildingPenalty: -1_000,
    futureBuildingWindow: 5,
    minimumStoneTarget: 18,
    futureStoneShare: 0.55,
  },
  buildingGoals: {
    utility: {
      huntingLodge: 188,
      orchard: 184,
      mill: 176,
      farm: 180,
      lumberMill: 178,
      kitchenBeforeGrowth: 172,
      house: 166,
      kitchen: 160,
      quarry: 146,
      fundedMarket: 156,
      market: 142,
      barracks: 138,
      mine: 128,
      smelter: 132,
      church: 82,
      defenseBarbican: 174,
      barbican: 105,
      defenseWall: 168,
      wall: 96,
      tower: 118,
    },
    farmDemandMultiplier: 1.35,
    lowWoodThreshold: 25,
    maximumLumberMills: 2,
    kitchenBeforeGrowthServiceSlack: 1,
    kitchenBeforeGrowthHousingSlack: 2,
    houseHousingSlack: 1,
    houseFutureService: 2,
    kitchenServiceSlack: 4,
    lowGoldMarketThreshold: 36,
    barracksMinimumPopulation: 3,
    industryFoodRunway: 3,
    smelterOreStock: 4,
    churchMinimumPopulation: 10,
    churchFoodRunway: 5,
    churchGoldRunway: 5,
    fortificationArmySize: 4,
    basicWallLimit: 2,
    completeWallLimit: 4,
    towerLimit: 2,
    towerArmySize: 6,
  },
  recruitment: {
    assaultReserveShare: 0.45,
    ordinaryReserveShare: 0.7,
    emergencyDefenseRadius: 3,
    emergencyDefensePowerRatio: 0.8,
    defenseUtility: 180,
    ordinaryUtility: 112,
  },
  taxation: {
    disableFoodRunway: 3.5,
    enableModerateFoodRunway: 5,
    enableExtortionateGoldRunway: 1.25,
    enableExtortionateFoodRunway: 7,
    disableExtortionateGoldRunway: 2.5,
    disableExtortionateFoodRunway: 5.5,
    emergencyReliefRunway: 2,
    recoveryUtility: 220,
    ordinaryUtility: 70,
  },
  market: {
    recruitmentFlourThreshold: 8,
    mobilizationBaseGold: 10,
    mobilizationReserveGoldShare: 0.1,
    minimumDefensePower: 6,
    defenseThreatPowerMultiplier: 1.15,
    defenseSupplyUtility: 214,
    mobilizationSupplyUtility: 154,
    saleBatch: 10,
    minimumSaleSurplus: 5,
    mobilizationSaleUtility: 158,
    emergencyFoodUtility: 210,
    stoneReserveGoldShare: 0.2,
    stoneUtility: 104,
    industrialIronTarget: 8,
    industrialIronGoldFloor: 60,
    industrialIronBatch: 5,
    industrialIronUtility: 92,
    upkeepGoldRunway: 2,
    recoverySaleUtility: 188,
    constructionGoldFloor: 32,
    constructionWoodBatch: 10,
    constructionUtility: 78,
  },
  placement: {
    targetDistanceWeight: 4,
    zoneCoverageWeight: 90,
    zoneDistanceWeight: 18,
    forestAdjacencyWeight: 28,
    forestDistanceWeight: 3,
    hillOpportunityWeight: 30,
    homeRadius: 8,
    homeProximityWeight: 2,
    barbicanChokeWeight: 4,
    wallChokeWeight: 2,
    wallFrontRadius: 10,
    towerVisibilityWeight: 0.8,
    towerHillWeight: 14,
    alignmentBonus: 6,
    quarterRadius: 10,
    quarterProximityWeight: 6,
    linkedDefenseRadius: 2,
    linkedDefenseWeight: 34,
    courtyardFoodRadius: 6,
    courtyardOrdinaryRadius: 3,
    courtyardRadiusPenalty: 2,
    strongpointFrontRadius: 12,
    strongpointFrontWeight: 0.5,
    minimumRecruitmentExits: 2,
    preferredZoneCoverage: 0.75,
    scanCheckInterval: 32,
    adaptiveShiftMinimum: 2,
    adaptiveShiftAreaDivisor: 2,
  },
  recovery: {
    dismissalUtility: 196,
    removeUnpaidChurchUtility: 212,
    removeIrrecoverableBuildingUtility: 132,
    excessBuildingUtility: { recovery: 128, stable: 76 },
    crowdedZoneUtility: { recovery: 122, stable: 68 },
    liquidationUtility: 94,
    redevelopmentUtility: 62,
    redevelopmentFoodRunway: 6,
    protectedBarracksCount: 1,
    retentionDefault: 45,
    retentionByKind: {
      lumberMill: 100,
      market: 100,
      house: 90,
      kitchen: 90,
      orchard: 80,
      huntingLodge: 80,
      farm: 80,
      mill: 80,
      barracks: 75,
      church: 10,
      wall: 20,
      tower: 20,
      barbican: 20,
    } as Partial<Record<BuildingKind, number>>,
    duplicateBarracksRetention: 30,
  },
  projection: {
    populationWeight: 22,
    armyPowerWeight: 13,
    resourceCaps: { wood: 180, stone: 120, iron: 80, gold: 180 },
    resourceWeights: { wood: 0.18, stone: 0.18, iron: 0.25, gold: 0.28 },
    foodCap: 220,
    foodWeight: 0.12,
    industrialIronWeight: 0.9,
    starvationPenalty: 650,
    unpaidUpkeepPenalty: 420,
    populationLossPenalty: 140,
    reserveScale: { recovery: 0.15, survival: 0.15, expansion: 0.75, mobilization: 0.75, assault: 0.55, regroup: 0.75, defense: 0.3 },
    reserveWeights: { wood: 0.8, stone: 1.4, ore: 0.7, iron: 2.4, flour: 0.9, meat: 0.7, fruit: 0.7, gold: 1.8 } satisfies Record<ResourceId, number>,
    excessiveHousingSlack: 10,
    excessiveHousingPenalty: 12,
    assaultArmyWeight: 5,
    defenseArmyWeight: 8,
  },
} as const

export const aiTacticalConfig = {
  targetPriority: {
    squadBase: 140,
    squadPerUnit: 8,
    castleBase: 105,
    damagedCastle: 0.8,
    towerBase: 88,
    towerPerGarrisonArcher: 12,
    barbican: 116,
    wall: 64,
    barracks: 102,
    strategicIndustry: 84,
    otherBuilding: 72,
  },
  evaluation: {
    ownPowerChange: 24,
    damage: 34,
    destructionPriority: 1.5,
    hill: 20,
    forestCover: 10,
    knightForest: -18,
    assaultProgress: 14,
    ordinaryProgress: 4,
    defenseRadius: 16,
    defenseProximity: 5,
    towerAttack: 28,
    defenseGarrison: 90,
    ordinaryGarrison: 38,
    replyPowerLoss: 28,
  },
  formation: {
    frontLineTroops: ['militia', 'spearmen', 'knights'] as readonly TroopKind[],
    fragileHealthShare: 0.55,
    rangedRoleShare: 0.4,
    retainedRangedRoleShare: 0.25,
    minimumReserveSquadShare: 0.25,
    reserveSquadShareMultiplier: 1.75,
    scoutMaximumSize: 2,
    scoutManeuverThreshold: 0.45,
    scoutMinimumGroups: 3,
    screenRadius: 3,
    maneuverRoleThreshold: 0.5,
    regroupUtility: 24,
    mobilizationBaseUtility: 18,
    mobilizationBiasUtility: 42,
    mergeBaseUtility: 20,
    fragileMergeUtility: 35,
    smallGroupSize: 6,
    smallGroupUtility: 3,
    splitMinimumSquadSize: 6,
    splitMinimumGroupPower: 2.5,
    splitMaximumPathOverlap: 0.55,
    splitDiversityUtility: 110,
    splitConcentrationCost: 48,
    splitTargetRiskCost: 32,
    splitExistingGroupCost: 8,
    stagingSplitRadius: 4,
    usefulGroupSize: 3,
    splitReadinessMultiplier: 0.9,
    splitRolePriority: 100,
    splitCompositionWeight: 10,
    splitPreferenceTieBreak: 0.01,
  },
  movement: {
    retreatUtility: 125,
    defenderUtility: 28,
    defenseProgressUtility: 18,
    mobilizationProgressUtility: 16,
    regroupProgressUtility: 18,
    peacefulProgressUtility: 8,
  },
  route: {
    musterRadius: 2,
    ordinaryApproachRadius: 3,
    reserveApproachRadius: 4,
    nearbySquadRadius: 2,
    routeLookahead: 8,
    forestLookahead: 6,
    spreadNeighborCap: 3,
    spreadUtility: 7,
    cohesionUtility: 9,
    knightForestPenalty: 5,
    pathLengthPenalty: 0.1,
    rememberedDangerRadius: 4,
    rememberedDangerUtility: 1.5,
    distantContactFallback: 20,
    scoutApproachMinimum: 2,
    ordinaryApproachMinimum: 1,
    peacefulHoldRadius: 3,
    mobilizationHoldRadius: 2,
    reserveHoldRadius: 3,
    overlapLookahead: 8,
  },
  siege: {
    breachOrderWeight: 1,
    routeBlockerPriorityBonus: 84,
    irrelevantStructurePenalty: 34,
  },
  staging: {
    corridorFrontShare: 0.55,
    maximumCorridorAnchors: 4,
    maximumAnchors: 5,
    minimumAnchorSpacing: 3,
    fallbackRadius: 10,
    assembledRadius: 4,
    fallbackFrontDistanceWeight: 2,
  },
  tower: {
    fireUtility: 80,
    releaseUtility: 72,
    defenseGarrisonUtility: 170,
    siegeRange: 6,
  },
} as const

export const aiProfiles: Record<AiProfileRules['id'], AiProfileRules> = {
  radomir: {
    id: 'radomir',
    arsenalTier: 'basic',
    allowedBuildings: ['orchard', 'huntingLodge', 'lumberMill', 'quarry', 'kitchen', 'house', 'barracks', 'market'],
    allowedTroops: ['militia', 'spearmen'],
    capabilities: { trade: true, demolition: true },
    allowedLayouts: ['courtyard', 'frontier'],
    preferredOpenings: ['forest', 'plains', 'highland'],
    doctrine: { preferredTroops: ['spearmen', 'militia'], targetComposition: { militia: 0.55, spearmen: 0.45 }, reserveShare: 0.12, retreatHealthShare: 0.3, targetStickiness: 0.22, maneuverBias: 0.35, concentrationBias: 0.8, marchingGroupBias: 0.6, probeRiskThreshold: 0.9, minimumProbePower: 8 },
    settlement: {
      areaScale: 0.82,
      zoneOriginTargets: { housing: 5, food: 3, industry: 2, military: 1, defense: 1 },
      buildingLimits: { house: 3, kitchen: 1, market: 1, orchard: 2, huntingLodge: 2, lumberMill: 2, quarry: 1, barracks: 1 },
      overflowRadius: { housing: 2, food: 3, industry: 3, military: 2, defense: 2 },
    },
    riskThreshold: 0.9,
    earliestOffensiveRound: 12,
    strategicReserve: { wood: 18, stone: 10, flour: 10, gold: 18 },
  },
  velislava: {
    id: 'velislava',
    arsenalTier: 'tactical',
    allowedBuildings: ['mill', 'farm', 'orchard', 'huntingLodge', 'lumberMill', 'quarry', 'kitchen', 'house', 'barracks', 'market', 'wall', 'barbican'],
    allowedTroops: ['militia', 'spearmen', 'archers'],
    capabilities: { trade: true, demolition: true },
    allowedLayouts: ['courtyard', 'frontier', 'strongpoint'],
    preferredOpenings: ['plains', 'forest', 'highland'],
    doctrine: { preferredTroops: ['archers', 'spearmen', 'militia'], targetComposition: { militia: 0.15, spearmen: 0.4, archers: 0.45 }, reserveShare: 0.2, retreatHealthShare: 0.38, targetStickiness: 0.3, maneuverBias: 0.85, concentrationBias: 0.5, marchingGroupBias: 1, probeRiskThreshold: 0.6, minimumProbePower: 5.5 },
    settlement: {
      areaScale: 1,
      zoneOriginTargets: { housing: 6, food: 6, industry: 3, military: 1, defense: 5 },
      buildingLimits: { house: 4, kitchen: 1, market: 1, mill: 2, farm: 4, orchard: 2, huntingLodge: 2, lumberMill: 2, quarry: 2, barracks: 1, wall: 4, barbican: 1 },
      overflowRadius: { housing: 2, food: 4, industry: 3, military: 2, defense: 3 },
    },
    riskThreshold: 1.05,
    earliestOffensiveRound: 8,
    strategicReserve: { wood: 24, stone: 18, iron: 2, flour: 14, gold: 26 },
  },
  svyatobor: {
    id: 'svyatobor',
    arsenalTier: 'complete',
    allowedBuildings: ['mill', 'farm', 'orchard', 'huntingLodge', 'lumberMill', 'quarry', 'mine', 'smelter', 'kitchen', 'house', 'barracks', 'church', 'market', 'wall', 'tower', 'barbican'],
    allowedTroops: ['militia', 'spearmen', 'archers', 'knights'],
    capabilities: { trade: true, demolition: true },
    allowedLayouts: ['courtyard', 'frontier', 'strongpoint'],
    preferredOpenings: ['highland', 'plains', 'forest'],
    doctrine: { preferredTroops: ['knights', 'archers', 'spearmen', 'militia'], targetComposition: { militia: 0.15, spearmen: 0.3, archers: 0.3, knights: 0.25 }, reserveShare: 0.28, retreatHealthShare: 0.45, targetStickiness: 0.38, maneuverBias: 0.7, concentrationBias: 0.7, marchingGroupBias: 0.8, probeRiskThreshold: 0.7, minimumProbePower: 5.5 },
    settlement: {
      areaScale: 1.18,
      zoneOriginTargets: { housing: 8, food: 7, industry: 5, military: 2, defense: 9 },
      buildingLimits: { house: 5, kitchen: 2, market: 1, church: 1, mill: 2, farm: 4, orchard: 2, huntingLodge: 2, lumberMill: 2, quarry: 2, mine: 2, smelter: 2, barracks: 2, wall: 6, tower: 2, barbican: 2 },
      overflowRadius: { housing: 3, food: 4, industry: 4, military: 3, defense: 3 },
    },
    riskThreshold: 1.2,
    earliestOffensiveRound: 6,
    strategicReserve: { wood: 30, stone: 22, ore: 5, iron: 8, flour: 16, meat: 4, gold: 34 },
  },
}

export const defaultOpponentProfileIds = ['radomir'] as const

export const aiAvatarPaths: Record<AiProfileRules['id'], string> = {
  radomir: 'assets/opponents/radomir.webp',
  velislava: 'assets/opponents/velislava.webp',
  svyatobor: 'assets/opponents/svyatobor.webp',
}
