import type { BuildingKind, ResourceId, TroopKind } from '../game/map'
import type {
  AiLayoutKind,
  AiOpeningKind,
  AiProfileRules,
  AiSettlementZoneKind,
} from '../game/ai/model'

export const aiPlannerConfig = {
  // UI threshold only. Crossing it shows that the lord is still thinking; it
  // never truncates search or changes the chosen plan.
  softBudgetMs: 3_000,
  projectionTurns: 4,
  stableRecoveryTurns: 3,
  foodRunwayTurns: 3,
  assaultFoodRunwayTurns: 4,
  goldRunwayTurns: 3,
  targetChangeMargin: 0.18,
  readinessEstimateTolerance: 0.03,
  targetMemoryTurns: 8,
  maximumRememberedContacts: 256,
  maximumBlockedCells: 32,
  blockedCellMemoryTurns: 2,
  maximumRecentMovements: 32,
  movementHistoryTurns: 3,
  maximumCommands: 18,
  // A plan is produced from fog-limited information. If a move reveals a
  // hidden blocker or costs more orders than projected, discard the stale
  // suffix and calculate once more from the authoritative intermediate state.
  maximumPlanAttempts: 2,
  minimumTaxHoldTurns: 3,
  forcedAdvanceAfterIdleTurns: 2,
  stalledMobilizationProbeTurns: 6,
  retargetAfterIdleTurns: 6,
  settlementPlanReviewInterval: 25,
  // Strategic search is model-predictive: it evaluates several future owner
  // turns, executes only the first turn, then replans from authoritative state.
  // These values define the model being evaluated, rather than interrupting a
  // calculation after an arbitrary amount of time or visited nodes.
  strategicLookaheadTurns: 2,
  strategicCurrentForecastWidth: 5,
  strategicFutureCandidateWidth: 3,
  strategicFutureDiscount: 0.9,
  relaxBlueprintAfterStalledTurns: 4,
  armyReorganizationCooldownTurns: 4,
  ordinaryTacticalOrderReserve: 2,
  assaultOrderReserve: 4,
  // Ordinary defense preserves room for a heavy forest move. When the next
  // affordable fortification step is a tower, the planner raises this reserve
  // to `defenseTowerOrderReserve` for that turn only.
  defenseStrategicOrderReserve: 4,
  defenseTowerOrderReserve: 6,
  strategicSearchDepth: 5,
  strategicBeamWidth: 8,
  candidatePriorScale: 0.12,
  candidatePriorLimit: 24,
  tacticalGuardMultiplier: 2,
  forcedAdvanceMinimumScore: -80,
  emergencyRunwayTurns: 1.5,
  defenseSupplyUtilityBonus: 20,
  defenseRecruitUtilityBonus: 35,
  productiveTradeRunwayDelta: 0.5,
  // Cooldown between successive "main" assault waves. Without this, an army in
  // the assault phase alternates main<->support every turn and looks like an
  // unbroken stream of reinforcements rather than a sequence of prepared,
  // assembled strikes. A support wave during the cooldown still advances the
  // siege, but gives the AI a moment to accumulate before the next main push.
  mainWaveCooldownTurns: 2,
} as const

export const aiBuildingKindsByZone = {
  housing: ['house', 'kitchen', 'market', 'church'],
  food: ['orchard', 'huntingLodge', 'mill', 'farm'],
  industry: ['lumberMill', 'quarry', 'mine', 'smelter'],
  military: ['barracks'],
  defense: ['wall', 'tower', 'barbican'],
} as const satisfies Record<AiSettlementZoneKind, readonly BuildingKind[]>

export const aiBuildingZoneByKind = Object.fromEntries(
  (Object.entries(aiBuildingKindsByZone) as Array<[AiSettlementZoneKind, readonly BuildingKind[]]>)
    .flatMap(([zone, kinds]) => kinds.map((kind) => [kind, zone])),
) as Record<BuildingKind, AiSettlementZoneKind>

export const aiSpatialConfig = {
  lineOfFireRayLength: 10,
  choke: {
    blockedNeighborBase: 4,
    blockedNeighborWeight: 7,
    frontLineBase: 8,
    frontLineDistanceWeight: 0.08,
  },
  layoutScore: {
    courtyard: { plain: 100, passableCap: 30, passableDivisor: 20, choke: -1 },
    frontier: { mixedTerrain: 65, distanceCap: 35, distance: 0.5 },
    strongpoint: { choke: 4, hill: 70, nonPlain: 20 },
  },
  openingScore: {
    forest: { coverage: 130, nearbyDistance: 12, proximity: 4 },
    plains: { coverage: 110 },
    highland: { coverage: 130, nearbyDistance: 12, proximity: 4 },
  } satisfies Record<AiOpeningKind, Record<string, number>>,
  preferenceBonus: 2,
  preferredSiteDistance: { housing: 3, food: 6, industry: 6, industryFallback: 7, military: 4 },
  gateCorridorShare: 0.35,
  regionScale: { minimum: 0.8, maximum: 1.35, referenceCells: 1_200, mediumThreshold: 1.12, largeThreshold: 1.32 },
  regionOriginGrowth: { medium: 1, large: 2 },
  minimumZoneArea: 8,
  baseZoneArea: { housing: 18, food: 28, industry: 18, military: 15, defense: 16 } satisfies Record<AiSettlementZoneKind, number>,
  layoutAreaScale: {
    courtyard: { housing: 1.12, food: 1.08, industry: 0.9, military: 1, defense: 0.82 },
    frontier: { housing: 1, food: 1, industry: 1.12, military: 1.05, defense: 1.05 },
    strongpoint: { housing: 0.92, food: 0.94, industry: 1, military: 1.12, defense: 1.28 },
  } satisfies Record<AiLayoutKind, Record<AiSettlementZoneKind, number>>,
  cellsPerOrigin: { housing: 2.5, food: 4, industry: 2, military: 6, defense: 1.5 } satisfies Record<AiSettlementZoneKind, number>,
  hillOpportunityCost: { base: 18, scarcity: 45 },
  settlementPlan: {
    scoreTieEpsilon: 0.0001,
    profileSeedMultiplier: 31,
    siteChokeWeight: 0.05,
    ordinaryHillPenalty: 5,
    industryMissingTerrainPenalty: 3,
    defenseChokeWeight: -0.08,
    ordinaryChokeWeight: 0.04,
    fortification: {
      minimumCastleDistance: 3,
      maximumCorridorShare: 0.62,
      minimumWalls: 2,
      // Delay walls may deliberately be long. The construction planner still
      // builds one funded segment at a time, so this is a geometric ceiling,
      // not permission to spend the survival stockpile in one turn.
      maximumWallsPerLine: 14,
      enclosureHalfExtents: [
        { columns: 1, rows: 2 },
        { columns: 2, rows: 1 },
        { columns: 2, rows: 2 },
        { columns: 2, rows: 3 },
        { columns: 3, rows: 2 },
      ],
      enclosureTowerCount: 2,
      // Seeded variation only chooses between already validated enclosure
      // plans. The structural invariants (closed perimeter, usable gate and
      // tower count) are checked before any of these soft preferences apply.
      enclosureGateCandidates: 4,
      enclosureAlignedOrientationBonus: 180,
      enclosureCorridorGateBonus: 120,
      enclosureGateFrontDistanceWeight: 12,
      enclosureTowerCornerBonus: 100,
      enclosureTowerFrontBonus: 80,
      enclosureTowerVariation: 140,
      enclosurePlanVariation: 480,
      enclosureInteriorDevelopmentWeight: 14,
      enclosureOpenPerimeterWeight: 12,
      enclosureAnchoredCompactWeight: 40,
      curtainShapeVariation: 220,
      curtainWingDelayBonus: 10,
      curtainDoctrineBonus: 420,
      curtainOpenWingBonus: 280,
      curtainAnchoredStraightBonus: 250,
      naturalAnchorBonus: 18,
      chokeWeight: 5,
      preferredDistanceWeight: 2,
      wallCountBonus: 6,
      pathDelayWeight: 14,
      sealedApproachBonus: 90,
      minimumPathDelay: 2,
      weakLinePenalty: 30,
      minimumLineSpacing: 6,
      outworkMinimumLineSpacing: 3,
      outpostMinimumCastleDistance: 7,
      outpostMaximumAssetDistance: 6,
      outpostHillBonus: 48,
      outpostLineOfFireWeight: 1.5,
      outpostAssetDistanceWeight: 5,
      outpostRemotenessWeight: 0.75,
    },
  },
} as const

export const aiStrategicConfig = {
  workerReserve: 2,
  populationGrowthLookahead: 2,
  maximumBuildingGoalsPerSearch: 6,
  buildingPlacementShortlist: 1_200,
  adaptiveBlueprintExpansionLimit: 4,
  maximumFoodFallbackBuildings: 2,
  minimumRunwayFlowMagnitude: 0.5,
  minimumCivilianReserve: 2,
  maximumRecruitBatch: 3,
  recruitmentCellCapacity: 10,
  basicMilitiaBeforeBarracks: 2,
  minimumAdvancedTroopsForPreferredArmy: 2,
  emergencyFoodBatch: 5,
  constructionWoodFloor: 20,
  constructionPlanningHorizonTurns: 24,
  operationalFoodBuildings: ['orchard', 'huntingLodge', 'farm'] as readonly BuildingKind[],
  crisisProductionBuildings: ['orchard', 'huntingLodge', 'farm', 'mill', 'kitchen', 'lumberMill'] as readonly BuildingKind[],
  restorableCapabilities: [
    'orchard', 'huntingLodge', 'mill', 'farm', 'kitchen', 'house',
    'lumberMill', 'quarry', 'mine', 'smelter', 'market', 'barracks',
  ] as readonly BuildingKind[],
  basicFoodBuildings: ['orchard', 'huntingLodge'] as readonly BuildingKind[],
  minimumFieldArmySize: 4,
  openingBuildingBonus: {
    forest: { huntingLodge: 20, lumberMill: 16, orchard: -4 },
    plains: { orchard: 18, mill: 14, farm: 14, huntingLodge: -4 },
    highland: { quarry: 18, mine: 14, orchard: 2, huntingLodge: 2 },
  } satisfies Record<AiOpeningKind, Partial<Record<BuildingKind, number>>>,
  // Keeps openings recognisably different without letting randomness defeat
  // hard survival, workforce, prerequisite or blueprint constraints.
  buildingGoalVariation: 24,
  threat: {
    immediateRadius: 12,
    evaluationRadius: 16,
    assumedOrdersPerTurn: 8,
    maximumArrivalTurns: 2,
  },
  power: {
    troopDamageWeight: 1.8,
    archerRangeBonus: 0.65,
    knightMobilityPenalty: 0.08,
    minimumHealthShare: 0.45,
    remainingHealthShare: 0.55,
    towerGarrisonMultiplier: 1.2,
  },
  phase: {
    regroupMinimumPower: 6,
    regroupTargetRatio: 0.55,
    campaignGoldRunway: 2,
    directDoctrineManeuverCutoff: 0.5,
    assemblyBaseShare: 0.65,
    assemblyManeuverDiscount: 0.2,
    assemblyMusterBonus: 0.15,
  },
  targetPower: {
    minimum: 8,
    castleBase: 8,
    castleHealthWeight: 0.04,
    wall: 3,
    barbican: 2,
    towerBase: 5,
    towerGarrisonArcher: 1.5,
  },
  targetSelection: {
    distanceWeight: 1.2,
    defensePowerWeight: 0.35,
    castleDamageWeight: 0.8,
    retaliationWindow: 8,
    stickinessScale: 20,
    minimumMemoryConfidence: 0.45,
  },
  resourcePlanning: {
    needWeights: { wood: 0.45, stone: 0.45, ore: 0.45, iron: 2, flour: 0.45, meat: 0.45, fruit: 0.45, gold: 1.3 } satisfies Record<ResourceId, number>,
    allowedBuildingBonus: 8,
    unavailableBuildingPenalty: -1_000,
    minimumStoneTarget: 18,
    futureStoneShare: 0.55,
  },
  buildingGoals: {
    utility: {
      huntingLodge: 188,
      orchard: 184,
      mill: 176,
      farm: 180,
      lumberMill: 178,
      kitchenBeforeGrowth: 172,
      house: 166,
      kitchen: 160,
      quarry: 146,
      fundedMarket: 156,
      market: 142,
      barracks: 138,
      // Once a settlement has already raised its militia screen or entered a
      // military phase, unlocking the real roster is more important than an
      // optional second food plot whose legal footprint may not exist.
      urgentBarracks: 206,
      mine: 128,
      // Once ore extraction exists, close the iron chain before filling every
      // optional housing slot; otherwise the complete profile can spend the
      // whole midgame stockpiling unusable ore and still field basic troops.
      smelter: 198,
      church: 82,
      defenseBarbican: 174,
      barbican: 105,
      defenseWall: 168,
      wall: 96,
      tower: 118,
    },
    farmDemandMultiplier: 1.35,
    farmClusterPriorityBonus: 34,
    lowWoodThreshold: 25,
    maximumLumberMills: 2,
    kitchenBeforeGrowthServiceSlack: 1,
    kitchenBeforeGrowthHousingSlack: 2,
    houseHousingSlack: 1,
    // One spare served citizen is enough to place the next house. Requiring
    // two created a 9/10 capacity deadlock after recruitment: housing had room
    // for 9 civilians, food service for 10, and neither a house nor a kitchen
    // considered itself the correct next step.
    houseFutureService: 1,
    kitchenServiceSlack: 4,
    lowGoldMarketThreshold: 36,
    barracksMinimumPopulation: 3,
    barracksUrgentPopulation: 12,
    industryFoodRunway: 3,
    smelterOreStock: 4,
    churchMinimumPopulation: 10,
    churchFoodRunway: 5,
    churchGoldRunway: 5,
    fortificationArmySize: 4,
    towerArmySize: 6,
    enclosureMinimumHouses: 3,
    enclosureMinimumQuarries: 2,
    fortificationContinuityBonus: 24,
    minimumViableFortificationWalls: 2,
  },
  recruitment: {
    civilianGrowthReserve: 3,
    emergencyCivilianReserve: 1,
    emergencyDraftAllowance: 6,
    criticalWorkerBuildings: ['mill', 'farm', 'orchard', 'huntingLodge', 'kitchen'] as readonly BuildingKind[],
    assaultReserveShare: 0.45,
    ordinaryReserveShare: 0.7,
    emergencyDefenseRadius: 3,
    emergencyDefensePowerRatio: 0.8,
    defensePowerMultiplier: 1.15,
    defenseUtility: 180,
    ordinaryUtility: 112,
  },
  taxation: {
    disableFoodRunway: 3.5,
    enableModerateFoodRunway: 7,
    emergencyReliefRunway: 2,
    recoveryUtility: 220,
    ordinaryUtility: 70,
  },
  market: {
    recruitmentFlourThreshold: 8,
    mobilizationBaseGold: 10,
    mobilizationReserveGoldShare: 0.1,
    minimumDefensePower: 6,
    defenseThreatPowerMultiplier: 1.15,
    defenseSupplyUtility: 214,
    mobilizationSupplyUtility: 154,
    saleBatch: 10,
    minimumSaleSurplus: 5,
    mobilizationSaleUtility: 158,
    emergencyFoodUtility: 210,
    stoneReserveGoldShare: 0.2,
    stoneUtility: 104,
    fortificationSupplyUtility: 164,
    industrialIronTarget: 8,
    industrialIronGoldFloor: 60,
    industrialIronBatch: 5,
    industrialIronUtility: 92,
    upkeepGoldRunway: 2,
    recoverySaleUtility: 188,
    constructionGoldFloor: 32,
    constructionWoodBatch: 10,
    constructionUtility: 78,
  },
  placement: {
    targetDistanceWeight: 4,
    zoneCoverageWeight: 90,
    zoneDistanceWeight: 18,
    forestAdjacencyWeight: 28,
    forestDistanceWeight: 3,
    hillOpportunityWeight: 30,
    homeRadius: 8,
    homeProximityWeight: 2,
    barbicanChokeWeight: 4,
    wallChokeWeight: 2,
    wallFrontRadius: 10,
    towerLineOfFireWeight: 0.8,
    towerHillWeight: 14,
    alignmentBonus: 6,
    quarterRadius: 10,
    quarterProximityWeight: 6,
    linkedDefenseRadius: 2,
    linkedDefenseWeight: 34,
    courtyardFoodRadius: 6,
    courtyardOrdinaryRadius: 3,
    courtyardRadiusPenalty: 2,
    strongpointFrontRadius: 12,
    strongpointFrontWeight: 0.5,
    minimumRecruitmentExits: 2,
    preferredZoneCoverage: 0.75,
    scanCheckInterval: 32,
    adaptiveShiftMinimum: 2,
    adaptiveShiftAreaDivisor: 2,
  },
  recovery: {
    meaningfulRunwayDelta: 0.25,
    dismissalUtility: 196,
    removeUnpaidChurchUtility: 212,
    removeIrrecoverableBuildingUtility: 132,
    excessBuildingUtility: { recovery: 128, stable: 76 },
    liquidationUtility: 94,
    protectedBarracksCount: 1,
  },
  projection: {
    populationWeight: 22,
    armyPowerWeight: 13,
    resourceCaps: { wood: 180, stone: 120, iron: 80, gold: 180 },
    resourceWeights: { wood: 0.18, stone: 0.18, iron: 0.25, gold: 0.28 },
    foodCap: 220,
    foodWeight: 0.12,
    industrialIronWeight: 0.9,
    starvationPenalty: 650,
    unpaidUpkeepPenalty: 420,
    populationLossPenalty: 140,
    reserveScale: { recovery: 0.15, survival: 0.15, expansion: 0.75, mobilization: 0.75, assault: 0.55, regroup: 0.75, defense: 0.3 },
    reserveWeights: { wood: 0.8, stone: 1.4, ore: 0.7, iron: 2.4, flour: 0.9, meat: 0.7, fruit: 0.7, gold: 1.8 } satisfies Record<ResourceId, number>,
    excessiveHousingSlack: 10,
    excessiveHousingPenalty: 12,
    assaultArmyWeight: 5,
    defenseArmyWeight: 8,
  },
  // Overdrive lets a fully-developed settlement keep growing reluctantly when
  // it is genuinely resource-rich: for every multiple of a building's cost held
  // in reserve, one extra slot opens on the housing/food/industry/military
  // zones. Defense (walls/towers/barbicans) is excluded — those follow the
  // fortification plan. Army size is deliberately not raised by overdrive, so
  // this adds economic depth without feeding the "endless wave spam" symptom.
  overdrive: {
    thresholds: [3, 6, 9] as const,
    bonusSlotsPerTier: [1, 2, 3] as const,
    minStableTurns: 3,
    // Typical per-building cost reference used to turn raw stockpiles into a
    // "how many copies could I afford right now" ratio. Picked from the median
    // economy building so the tier feels the same across profiles.
    costReference: { wood: 12, stone: 14, ore: 8, iron: 3, flour: 8, meat: 2, fruit: 4, gold: 24 } satisfies Record<ResourceId, number>,
  },
} as const

export const aiTacticalConfig = {
  targetPriority: {
    squadBase: 140,
    squadPerUnit: 8,
    castleBase: 105,
    damagedCastle: 0.8,
    towerBase: 88,
    towerPerGarrisonArcher: 12,
    barbican: 116,
    wall: 64,
    barracks: 102,
    strategicIndustry: 84,
    otherBuilding: 72,
  },
  evaluation: {
    ownPowerChange: 24,
    damage: 34,
    destructionPriority: 1.5,
    hill: 20,
    forestCover: 10,
    knightForest: -18,
    assaultProgress: 14,
    ordinaryProgress: 4,
    defenseRadius: 16,
    defenseProximity: 5,
    towerAttack: 28,
    defenseGarrison: 90,
    ordinaryGarrison: 38,
    replyPowerLoss: 28,
  },
  formation: {
    frontLineTroops: ['militia', 'spearmen', 'knights'] as readonly TroopKind[],
    fragileHealthShare: 0.55,
    rangedRoleShare: 0.4,
    retainedRangedRoleShare: 0.25,
    minimumReserveSquadShare: 0.25,
    reserveSquadShareMultiplier: 1.75,
    scoutMaximumSize: 2,
    scoutManeuverThreshold: 0.45,
    scoutMinimumGroups: 3,
    screenRadius: 3,
    rangedWithdrawalThreatDistance: 4,
    maneuverRoleThreshold: 0.5,
    regroupUtility: 24,
    mobilizationBaseUtility: 18,
    mobilizationBiasUtility: 42,
    mergeBaseUtility: 20,
    fragileMergeUtility: 35,
    smallGroupSize: 6,
    smallGroupUtility: 3,
    splitMinimumSquadSize: 6,
    splitMinimumGroupPower: 2.5,
    splitMaximumPathOverlap: 0.55,
    splitMinimumDestinationSeparation: 4,
    splitMinimumRouteLength: 5,
    splitDiversityUtility: 110,
    splitConcentrationCost: 48,
    splitTargetRiskCost: 32,
    splitExistingGroupCost: 8,
    stagingSplitRadius: 4,
    usefulGroupSize: 3,
    splitReadinessMultiplier: 0.9,
    splitRolePriority: 100,
    splitCompositionWeight: 10,
    splitPreferenceTieBreak: 0.01,
    supportAssemblyTargetRatioMinimum: 0.35,
    supportAssemblyTargetRatioMaximum: 0.65,
    finisherHealthShare: 0.4,
    finisherMaximumSize: 3,
    finisherUtility: 42,
  },
  movement: {
    retreatUtility: 125,
    // Formation actions must outrank another attractive archer volley: the
    // screen is established first, then the remaining orders can be spent on
    // fire. Withdrawal is deliberately limited to one step per ranged squad
    // per turn in tactics, so these are priorities rather than kite loops.
    rangedWithdrawalUtility: 350,
    rangedWithdrawalDistanceUtility: 35,
    screenUtility: 400,
    screenProgressUtility: 40,
    defenderUtility: 28,
    defenseEngagementUtility: 110,
    defenseProgressUtility: 18,
    mobilizationProgressUtility: 16,
    regroupProgressUtility: 18,
    peacefulProgressUtility: 8,
  },
  route: {
    musterRadius: 2,
    ordinaryApproachRadius: 3,
    reserveApproachRadius: 4,
    nearbySquadRadius: 2,
    routeLookahead: 8,
    forestLookahead: 6,
    spreadNeighborCap: 3,
    spreadUtility: 7,
    cohesionUtility: 9,
    knightForestPenalty: 5,
    pathLengthPenalty: 0.1,
    rememberedDangerRadius: 4,
    rememberedDangerUtility: 1.5,
    distantContactFallback: 20,
    scoutApproachMinimum: 2,
    ordinaryApproachMinimum: 1,
    peacefulHoldRadius: 3,
    mobilizationHoldRadius: 2,
    reserveHoldRadius: 3,
    overlapLookahead: 8,
  },
  siege: {
    breachOrderWeight: 1,
    routeBlockerPriorityBonus: 84,
    routeThreatPriorityBonus: 70,
    towerExposureOrderCostPerArcher: 1.6,
    towerExposureRoutePenalty: 1.25,
    towerExposureLookahead: 10,
  },
  raid: {
    maximumTargets: 6,
    borderScanRadius: 8,
    localThreatRadius: 8,
    responseMargin: 2,
    minimumGroupPower: 2.5,
    mainWaveMinimumBias: 0.65,
    targetValues: {
      mill: 140,
      kitchen: 128,
      smelter: 122,
      mine: 108,
      farm: 96,
      orchard: 90,
      huntingLodge: 90,
      lumberMill: 86,
      quarry: 82,
      market: 78,
      church: 70,
      house: 58,
    } as Partial<Record<BuildingKind, number>>,
    castleIsolationBonus: 2.5,
    borderExposureBonus: 3,
    pathOrderPenalty: 3.5,
    breachOrderPenalty: 5,
    localThreatPenalty: 55,
    responsePenalty: 7,
    towerThreatPower: 5,
    objectiveProgressUtility: 26,
    objectiveBaseUtility: 14,
    objectiveScoreUtilityScale: 0.08,
    objectiveScoreUtilityCap: 20,
    targetAttackBonus: 96,
    opportunityAttackBonus: 52,
    opportunityChance: 0.58,
    opportunityMaximumChance: 0.82,
    opportunityMaximumOrders: 3,
    opportunityPathRadius: 1,
    opportunityThreatRadius: 4,
    opportunityMaximumThreatRatio: 0.7,
    minimumObjectiveScore: 28,
    scoutMultiplier: 1.15,
    probeMultiplier: 1,
    mainMultiplier: 0.55,
    supportMultiplier: 0.7,
    // Once an assault reaches siege range, scouts and detached groups should
    // still raid undefended economy near the enemy castle instead of standing
    // idle at the gates. The multiplier is deliberately low so the main body
    // stays focused on the siege; only cheap opportunistic raids bleed through.
    overrunMultiplier: 0.3,
  },
  staging: {
    corridorFrontShare: 0.55,
    maximumCorridorAnchors: 4,
    maximumAnchors: 5,
    minimumAnchorSpacing: 3,
    fallbackRadius: 10,
    assembledRadius: 4,
    fallbackFrontDistanceWeight: 2,
  },
  tower: {
    fireUtility: 80,
    releaseUtility: 72,
    defenseGarrisonUtility: 170,
    peacetimeGarrisonUtility: 104,
    minimumPeacetimeArchers: 2,
    siegeRange: 6,
  },
  defense: {
    coreBreachRadius: 2,
    coreBreachMinimumContactPowerRatio: 0.3,
    coreBreachEngagementUtility: 600,
    contactCommitmentUtility: 180,
    contactExchangeUtility: 18,
    concentrationPowerUtility: 40,
    certainDestructionPenalty: 1_000,
    rangedExposureRoutePenalty: 12,
    rangedExposureLookahead: 8,
    remoteGuardMinimumCastleDistance: 6,
    maximumPropertyAnchors: 3,
    propertyExposureWeight: 9,
    threatDistancePenalty: 9,
    assetValues: {
      castle: 180,
      tower: 150,
      barbican: 135,
      barracks: 125,
      mine: 118,
      smelter: 116,
      mill: 112,
      lumberMill: 108,
      quarry: 104,
      farm: 96,
      orchard: 88,
      huntingLodge: 88,
      kitchen: 82,
      market: 76,
      church: 72,
      house: 48,
      wall: 32,
    } satisfies Partial<Record<BuildingKind | 'castle', number>>,
  },
} as const

export const aiProfiles: Record<AiProfileRules['id'], AiProfileRules> = {
  radomir: {
    id: 'radomir',
    arsenalTier: 'basic',
    allowedBuildings: ['orchard', 'huntingLodge', 'lumberMill', 'quarry', 'kitchen', 'house', 'barracks', 'market'],
    allowedTroops: ['militia', 'spearmen'],
    capabilities: { trade: true, demolition: true },
    allowedLayouts: ['courtyard', 'frontier'],
    preferredOpenings: ['forest', 'plains', 'highland'],
    doctrine: {
      preferredTroops: ['spearmen', 'militia'],
      defensiveTroops: ['spearmen', 'militia'],
      targetComposition: { militia: 0.55, spearmen: 0.45 },
      defenseForceShare: 0.22,
      propertyGuardShare: 0,
      raidForceShare: 0.24,
      retreatHealthShare: 0.3,
      targetStickiness: 0.22,
      maneuverBias: 0.35,
      concentrationBias: 0.8,
      raidBias: 0.35,
      finisherBias: 0.85,
      musterBias: 0.9,
      marchingGroupBias: 0.8,
      probeRiskThreshold: 0.9,
      forceTargets: {
        probe: { minimum: 7, preferred: 9, maximum: 13 },
        raid: { minimum: 8, preferred: 11, maximum: 16 },
        assault: { minimum: 12, preferred: 18, maximum: 26 },
        defense: { minimum: 5, preferred: 9, maximum: 14 },
      },
      offensivePauseTurns: 3,
    },
    settlement: {
      areaScale: 0.82,
      fortificationPattern: 'none',
      maximumCurtainWingDepth: 0,
      surplusFortificationStoneReserve: 0,
      remoteTowerLimit: 0,
      zoneOriginTargets: { housing: 6, food: 4, industry: 3, military: 1, defense: 1 },
      buildingLimits: { house: 5, kitchen: 1, market: 1, orchard: 2, huntingLodge: 2, lumberMill: 2, quarry: 1, barracks: 1 },
      overflowRadius: { housing: 2, food: 3, industry: 3, military: 2, defense: 2 },
    },
    developmentMilestones: [
      { round: 0, economyBonusSlots: 0, housingBonusSlots: 0, armyCeiling: 16 },
      { round: 100, economyBonusSlots: 1, housingBonusSlots: 2, armyCeiling: 22 },
      { round: 200, economyBonusSlots: 2, housingBonusSlots: 4, armyCeiling: 28 },
      { round: 300, economyBonusSlots: 3, housingBonusSlots: 6, armyCeiling: 34 },
    ],
    taxation: { maximumRate: 'moderate', maximumRateFoodRunway: 7, desiredGoldRunway: 2 },
    riskThreshold: 0.9,
    earliestOffensiveRound: 12,
    strategicReserve: { wood: 18, stone: 10, flour: 10, gold: 18 },
  },
  velislava: {
    id: 'velislava',
    arsenalTier: 'tactical',
    allowedBuildings: ['mill', 'farm', 'orchard', 'huntingLodge', 'lumberMill', 'quarry', 'kitchen', 'house', 'barracks', 'market', 'wall', 'barbican'],
    allowedTroops: ['militia', 'spearmen', 'archers'],
    capabilities: { trade: true, demolition: true },
    allowedLayouts: ['courtyard', 'frontier', 'strongpoint'],
    preferredOpenings: ['plains', 'forest', 'highland'],
    doctrine: {
      preferredTroops: ['archers', 'spearmen', 'militia'],
      defensiveTroops: ['archers', 'spearmen', 'militia'],
      targetComposition: { militia: 0.15, spearmen: 0.4, archers: 0.45 },
      defenseForceShare: 0.28,
      propertyGuardShare: 0.1,
      raidForceShare: 0.36,
      retreatHealthShare: 0.38,
      targetStickiness: 0.3,
      maneuverBias: 0.85,
      concentrationBias: 0.5,
      raidBias: 1,
      finisherBias: 0.65,
      musterBias: 0.72,
      marchingGroupBias: 1,
      probeRiskThreshold: 0.6,
      forceTargets: {
        probe: { minimum: 5.5, preferred: 8, maximum: 15 },
        raid: { minimum: 8, preferred: 14, maximum: 20 },
        assault: { minimum: 15, preferred: 23, maximum: 34 },
        defense: { minimum: 7, preferred: 13, maximum: 20 },
      },
      offensivePauseTurns: 2,
    },
    settlement: {
      areaScale: 1,
      fortificationPattern: 'curtain',
      maximumCurtainWingDepth: 3,
      surplusFortificationStoneReserve: 0,
      remoteTowerLimit: 0,
      zoneOriginTargets: { housing: 8, food: 10, industry: 4, military: 1, defense: 5 },
      buildingLimits: { house: 7, kitchen: 2, market: 1, mill: 2, farm: 4, orchard: 2, huntingLodge: 2, lumberMill: 2, quarry: 2, barracks: 1, wall: 14, barbican: 1 },
      overflowRadius: { housing: 2, food: 4, industry: 3, military: 2, defense: 3 },
    },
    developmentMilestones: [
      { round: 0, economyBonusSlots: 0, housingBonusSlots: 0, armyCeiling: 20 },
      { round: 100, economyBonusSlots: 1, housingBonusSlots: 3, armyCeiling: 30 },
      { round: 200, economyBonusSlots: 2, housingBonusSlots: 6, armyCeiling: 40 },
      { round: 300, economyBonusSlots: 3, housingBonusSlots: 9, armyCeiling: 50 },
    ],
    taxation: { maximumRate: 'extortionate', maximumRateFoodRunway: 8, desiredGoldRunway: 2.5 },
    riskThreshold: 1.05,
    earliestOffensiveRound: 8,
    strategicReserve: { wood: 24, stone: 18, iron: 2, flour: 14, gold: 26 },
  },
  svyatobor: {
    id: 'svyatobor',
    arsenalTier: 'complete',
    allowedBuildings: ['mill', 'farm', 'orchard', 'huntingLodge', 'lumberMill', 'quarry', 'mine', 'smelter', 'kitchen', 'house', 'barracks', 'church', 'market', 'wall', 'tower', 'barbican'],
    allowedTroops: ['militia', 'spearmen', 'archers', 'knights'],
    capabilities: { trade: true, demolition: true },
    allowedLayouts: ['courtyard', 'frontier', 'strongpoint'],
    preferredOpenings: ['highland', 'plains', 'forest'],
    doctrine: {
      preferredTroops: ['knights', 'archers', 'spearmen', 'militia'],
      defensiveTroops: ['archers', 'spearmen', 'knights', 'militia'],
      targetComposition: { militia: 0.15, spearmen: 0.3, archers: 0.3, knights: 0.25 },
      defenseForceShare: 0.3,
      propertyGuardShare: 0.26,
      raidForceShare: 0.3,
      retreatHealthShare: 0.45,
      targetStickiness: 0.38,
      maneuverBias: 0.7,
      concentrationBias: 0.7,
      raidBias: 0.8,
      finisherBias: 1,
      musterBias: 0.78,
      marchingGroupBias: 0.85,
      probeRiskThreshold: 0.7,
      forceTargets: {
        probe: { minimum: 6, preferred: 9, maximum: 14 },
        raid: { minimum: 10, preferred: 17, maximum: 25 },
        assault: { minimum: 20, preferred: 30, maximum: 44 },
        defense: { minimum: 9, preferred: 16, maximum: 26 },
      },
      offensivePauseTurns: 2,
    },
    settlement: {
      areaScale: 1.18,
      fortificationPattern: 'citadel-enclosure',
      maximumCurtainWingDepth: 0,
      surplusFortificationStoneReserve: 90,
      remoteTowerLimit: 1,
      zoneOriginTargets: { housing: 14, food: 10, industry: 8, military: 2, defense: 10 },
      buildingLimits: { house: 10, kitchen: 2, market: 1, church: 1, mill: 2, farm: 4, orchard: 2, huntingLodge: 2, lumberMill: 2, quarry: 2, mine: 2, smelter: 2, barracks: 2, wall: 24, tower: 4, barbican: 2 },
      overflowRadius: { housing: 3, food: 4, industry: 4, military: 3, defense: 3 },
    },
    developmentMilestones: [
      { round: 0, economyBonusSlots: 0, housingBonusSlots: 0, armyCeiling: 30 },
      { round: 100, economyBonusSlots: 1, housingBonusSlots: 4, armyCeiling: 40 },
      { round: 200, economyBonusSlots: 2, housingBonusSlots: 8, armyCeiling: 50 },
      { round: 300, economyBonusSlots: 3, housingBonusSlots: 12, armyCeiling: 60 },
    ],
    taxation: { maximumRate: 'extortionate', maximumRateFoodRunway: 6, desiredGoldRunway: 4 },
    riskThreshold: 1.2,
    earliestOffensiveRound: 6,
    strategicReserve: { wood: 30, stone: 22, ore: 5, iron: 8, flour: 16, meat: 4, gold: 34 },
  },
}

export const defaultOpponentProfileIds = ['radomir'] as const

export const aiAvatarPaths: Record<AiProfileRules['id'], string> = {
  radomir: 'assets/opponents/radomir.webp',
  velislava: 'assets/opponents/velislava.webp',
  svyatobor: 'assets/opponents/svyatobor.webp',
}
