export const gameConfig = {
  map: {
    columns: 100,
    rows: 100,
    cellSize: 50,
  },
  generator: {
    editorColumns: 12,
    editorRows: 12,
    defaultSeed: 4127,
    minMapSize: 50,
    maxMapSize: 150,
    defaultMapSize: 100,
  },
  match: {
    minParticipants: 2,
    maxParticipants: 4,
    defaultParticipants: 2,
    castleBoundaryBuffer: 2,
    regionSearchAttempts: 32,
    forestRegionValue: 0.75,
    hillRegionValue: 0.45,
    maxRegionQualityRatio: 1.18,
    maxRegionAreaRatio: 1.35,
    maxForestCoverageSpread: 0.65,
    maxHillCoverageSpread: 0.65,
    maxRegionCenterOffset: 0.58,
    maxRegionPerimeterRatio: 8,
  },
  turn: {
    maxOrders: 4,
  },
  audio: {
    defaultVolume: 70,
    volumeStorageKey: 'castle-turns:sound-volume',
    lastVolumeStorageKey: 'castle-turns:last-sound-volume',
    legacyEnabledStorageKey: 'castle-turns:sound-enabled',
    gainMultiplier: 2.8,
  },
  camera: {
    minZoom: 0.3,
    maxZoom: 1.5,
    foundingZoom: 0.9,
    gameStartZoom: 1.05,
    wheelSensitivity: 0.0015,
    dragThreshold: 5,
  },
  navigationHint: {
    storageKey: 'castle-turns:navigation-hint-seen',
    masteredDelayMs: 10_000,
    partialDelayMs: 60_000,
  },
  savedMaps: {
    storageKey: 'castle-turns:saved-maps',
  },
} as const
