export const gameIdentity = {
  name: 'Ваш приказ',
  englishName: 'Your Command',
  slug: 'your-command',
  version: '1.0.0',
} as const

const storageKey = (name: string) => `${gameIdentity.slug}:${name}`

export const gameConfig = {
  map: {
    columns: 100,
    rows: 100,
    cellSize: 50,
  },
  generator: {
    editorColumns: 12,
    editorRows: 12,
    defaultSeed: 4127,
    minMapSize: 50,
    maxMapSize: 150,
    defaultMapSize: 100,
  },
  match: {
    minParticipants: 2,
    maxParticipants: 4,
    defaultParticipants: 2,
    castleBoundaryBuffer: 2,
    regionSearchAttempts: 32,
    forestRegionValue: 0.75,
    hillRegionValue: 0.45,
    maxRegionQualityRatio: 1.18,
    maxRegionAreaRatio: 1.35,
    maxForestCoverageSpread: 0.65,
    maxHillCoverageSpread: 0.65,
    maxRegionCenterOffset: 0.58,
    maxRegionPerimeterRatio: 8,
    minimumClearStartCells: 24,
  },
  turn: {
    maxOrders: 8,
    movementOrderCost: 1,
    knightMovementOrderMultiplier: 2,
    forestMovementOrderMultiplier: 2,
    squadReorganizationOrderCost: 2,
    demolishOrderCost: 2,
    demolitionRefundRate: 0.5,
    archerRange: 8,
    squadCapacity: 10,
    castleHitPoints: 100,
    basePopulationCapacity: 5,
    startingPopulation: 5,
    opponentDelayMs: 1_000,
    autoMoveStepDelayMs: 300,
  },
  army: {
    capacity: 100,
  },
  economy: {
    civilianFoodPerPerson: 1,
    soldierFoodPerUnit: 1,
    foodResources: ['flour', 'meat', 'fruit'],
    diverseDietMinimumShare: 0.2,
    diverseDietPopulationGrowthBonus: 1,
    diverseDietDamageMultiplier: 1.05,
    basePopulationGrowth: 1,
    minimumPopulation: 1,
    starvationPopulationLoss: 1,
    castleFoodServiceCapacity: 10,
    foodServiceRadius: 5,
  },
  visibility: {
    buildingRadius: 8,
    squadRadius: 10,
    elevatedSquadRadius: 12,
    fogAlpha: 0.24,
    fogEdgeAlpha: 0.12,
  },
  audio: {
    defaultVolume: 70,
    volumeStorageKey: storageKey('sound-volume'),
    lastVolumeStorageKey: storageKey('last-sound-volume'),
    legacyVolumeStorageKey: 'castle-turns:sound-volume',
    legacyLastVolumeStorageKey: 'castle-turns:last-sound-volume',
    legacyEnabledStorageKey: 'castle-turns:sound-enabled',
    gainMultiplier: 2.8,
    musicDefaultVolume: 42,
    musicVolumeStorageKey: storageKey('music-volume'),
    musicCrossfadeMs: 1_800,
    combatMusicHoldMs: 12_000,
    musicTracks: {
      menu: 'assets/music/the-old-tower-inn.mp3',
      settlement: 'assets/music/woodland-fantasy.mp3',
      battle: 'assets/music/heroic-demise.mp3',
    },
  },
  camera: {
    minZoom: 0.3,
    maxZoom: 1.5,
    foundingZoom: 0.9,
    gameStartZoom: 1.05,
    wheelSensitivity: 0.0015,
    dragThreshold: 5,
    unitMoveAnimationMs: 260,
  },
  navigationHint: {
    storageKey: storageKey('navigation-hint-seen'),
    legacyStorageKey: 'castle-turns:navigation-hint-seen',
    masteredDelayMs: 10_000,
    partialDelayMs: 60_000,
  },
  display: {
    showGridByDefault: true,
    gridStorageKey: storageKey('map-grid-visible'),
  },
  savedMaps: {
    storageKey: storageKey('saved-maps'),
    legacyStorageKey: 'castle-turns:saved-maps',
  },
  savedGames: {
    databaseName: 'your-command',
    storeName: 'saved-games',
    version: 1,
  },
} as const
